/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufc.fbd.visao;

import ufc.fbd.modelo.Filme;

/**
 *
 * @author Luan
 */
public class PainelFilme extends javax.swing.JPanel {

    /**
     * Creates new form PainelFilme
     */
    
    private EventoCliqueFilme evento;
    private Filme filme;
    
    public PainelFilme(Filme filme, EventoCliqueFilme evento, boolean dispor) {
        this.evento = evento;
        this.filme = filme;
        initComponents();
        jlNome.setText(filme.getNome());
        jlClassificacao.setText("+"+filme.getIndicacao());
        
        if(filme.isAlugado() && dispor)
            ljDisponivel.setOpaque(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlImagem = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlClassificacao = new javax.swing.JLabel();
        ljDisponivel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(194, 279));
        setMinimumSize(new java.awt.Dimension(194, 275));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jlImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jlImagem);
        jlImagem.setBounds(14, 15, 166, 220);

        jlNome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jlNome.setText("NOME");
        add(jlNome);
        jlNome.setBounds(14, 248, 132, 16);

        jlClassificacao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jlClassificacao.setText("+18");
        add(jlClassificacao);
        jlClassificacao.setBounds(153, 248, 27, 16);

        ljDisponivel.setBackground(new java.awt.Color(255, 0, 0));
        add(ljDisponivel);
        ljDisponivel.setBounds(180, 0, 20, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        evento.cliqueFilme(filme);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlClassificacao;
    private javax.swing.JLabel jlImagem;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel ljDisponivel;
    // End of variables declaration//GEN-END:variables
}
